[tool.mypy]
ignore_missing_imports = true
strict = true
exclude = [
    "venv",
    "^semantic_domain.*\\.py$"
]

[tool.black]
line-length = 99
target-version = ["py38", "py39", "py310"]

[tool.isort]
profile = "black"
line_length = 99
force_sort_within_sections = true
src_paths = ["docx_to_xml"]
skip_gitignore = true
