[tool.mypy]
ignore_missing_imports = true
strict = true

[[tool.mypy.overrides]]
module = "semantic_domain"
ignore_errors = true

[[tool.mypy.overrides]]
module = "semantic_domain_subs"
ignore_errors = true

[[tool.mypy.overrides]]
module = "docx_to_xml.semantic_domain_xml"
ignore_errors = true

[tool.black]
line-length = 99
target-version = ["py38", "py39", "py310"]

[tool.isort]
profile = "black"
line_length = 99
force_sort_within_sections = true
src_paths = ["docx_to_xml"]
skip_gitignore = true
